_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.8
            "6": 4.50.0
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": linux-x86_64
DATA:
    value: namespace(WINDOW_LENGTH=7, DATA_IDX_DIR='/mnt/disk3/tunm/Subseasonal_Forecasting/data3/data6789_reg_1_seed52_new_all', GAUGE_DATA_PATH='/mnt/disk3/longnd/env_data/Gauge_thay_Tan/Final_Data_2002_2024_Region_1.csv', NPYARR_DIR='/mnt/disk3/longnd/env_data/grid_base/nparr_reg1/Step24h', PROCESSED_ECMWF_DIR='/mnt/disk3/longnd/env_data/grid_base/data3_reg_1_new_all', ESP_DATA_PATH='/mnt/disk3/longnd/env_data/grid_base/GMSaP/preprocess_region_1', LAT_START=23.25, LON_START=102.25, LAT_ESP_START=23.25, LON_ESP_START=102.25, HEIGHT=25, WIDTH=25, HEIGHT_ESP=30, WIDTH_ESP=30, RAIN_PROB=0.01, RAIN_THRESHOLD=300)
DEBUG:
    value: true
DEVICE:
    value: cuda
EARLY_STOPPING:
    value: namespace(PATIANCE=10, CHECKPOINT_DIR='checkpoint', DELTA=0.0)
LOSS:
    value: namespace(NAME='weightedmse', k=0.1, HIGH_WEIGHT=20, LOW_WEIGHT=1, DELTA=2.5, ALPHA=0.5, GROUNDTRUTH_THRESHOLD=200, WEIGHT_FUNC='abs')
LRS:
    value: namespace(USE_LRS=True, NAME='ReduceLROnPlateau', COSINE_T_MAX=0.001, COSINE_ETA_MIN=1e-05, PLATEAU_MODE='min', PLATEAU_FACTOR=0.5, PLATEAU_PATIENCE=3, PLATEAU_MIN_LR=1e-09, PLATEAU_VERBOSE=True)
MODEL:
    value: namespace(NAME='quantitle', SEED=52, IN_CHANNEL=13, ECMWF_TIME_STEP=7, TIME_STEP=7, PHASE_1_PATH='saved_checkpoints_phase_1/data3-r1-test-vit-tiny-short/checkpoint/BATCH_64_Add_type_0data3-r1-test-vit-tiny-short_VIT_2Head_PS-3_Lr-2e-05_LF-weightedmse-wfn_abs_DR-0.25_LN-True-ST_0_3-ON_True_Seed-52_LRS-TrueGSMAP_time_step2ECMWF_time_step1_ReduceLROnPlateau-min-0.5-3VIT_Blocks_2.pt', SPATIAL=namespace(TYPE=0, OUT_CHANNEL=64, NUM_LAYERS=3, USE_BATCH_NORM=False, KERNEL_SIZES=[1, 3, 5]), TEMPORAL=namespace(HIDDEN_DIM=256, NUM_LAYERS=2, MAX_DELTA_T=46, ADDING_TYPE=0), SWIN_TRANSFORMER=namespace(EMBED_DIM=128, NUM_HEADS=8, NUM_LAYERS=4, FF_DIM=256, WINDOW_SIZE=7), RADIUS=1, PRED=namespace(NUM_LAYERS=8, HIDDEN_DIM=64), PROMPT_TYPE=0, USE_LAYER_NORM=True, DROPOUT=0.26, WINDOW_SIZE=7, NUM_HEADS=4, PATCH_SIZE=3, R=32, RAIN_THRESHOLD=1)
OPTIMIZER:
    value: namespace(NAME='adamw', LR=5e-05, L2_COEF=1e-06, L1_COEF=0.0001)
TRAIN:
    value: namespace(OUTPUT_NORM=True, BATCH_SIZE=32, EPOCHS=1000, WARMUP_EPOCHS=10, MIN_LR=1e-05, WEIGHT_DECAY=0.05, LAYER_DECAY=0.8, NUMBER_WORKERS=0, INPUT_NORM=False, NUM_VITBLOCKS=2)
WANDB:
    value: namespace(STATUS=True, GROUP_NAME='data3-r1-test-vit-tiny-all-weekly', SESSION_NAME='BATCH_32_Add_type_0data3-r1-test-vit-tiny-all-weekly_Modelv1_PS-3_Lr-5e-05_LF-weightedmse-wfn_abs_DR-0.26_LN-True-ST_0_3-ON_True_Seed-52_LRS-TrueGSMAP_time_step7ECMWF_time_step7_ReduceLROnPlateau-min-0.5-3VIT_Blocks_2')
